### ISSUE TITLE
➕ Add Telos, Core, and Rootstock Main Network Deployments

### ISSUE THREAD

**Issue by dzaptech** [pcaversaccio/create2deployer#193]
Telos - https://chainlist.org/chain/40
Core - https://chainlist.org/chain/1116
RootStock - https://chainlist.org/chain/30

Also would like to understand that does the deployer account of create2 matters?
Like I deployed Create2 from your repo on Telos and then deployed a contract using that deployer with same salt and codeHash but I did not get same address. Anyway to handle this thing in future or would need to request here itself?

**Comment by pcaversaccio** [comment]
@dzaptech please fund my deployer address `0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad` on all three chains; 0.15 ETH/native currency should be enough as long as the chain is EVM equivalent.

You can't deploy yourself the contract factory from another address since this will result in another contract factory address which however must be the same as for the other deployments in order to give you the same address at deployment of your contract. As a reminder:

- [`CREATE`](https://www.evm.codes/#f0?fork=shanghai): `address computedAddress = keccak256(rlpEncode([deployerAddress, deployerNonce]))[12:]`,
- [`CREATE2`](https://www.evm.codes/#f5?fork=shanghai): `address computedAddress = keccak256(0xff||deployerAddress||salt||keccak256(initCode))[12:]`.

The `deployerAddress` is the contract factory address if you call `deploy` in the `Create2Deployer`.

**Comment by dzaptech** [comment]
Core and Telos team has added the tokens in above address. Still waiting for RootStock. 
Can you please deploy it on Telos and Core and I'll reply back here once RS send the funds.

**Comment by dzaptech** [comment]
Hi @pcaversaccio the respective teams have added funds in your wallet.

**Comment by pcaversaccio** [comment]
> Hi @pcaversaccio the respective teams have added funds in your wallet.

Deployed on all the main and test networks: https://github.com/pcaversaccio/create2deployer/commit/eeda076c0fee3017930eb86d27616dc508bbfc90.
