### ISSUE TITLE
Enforcing front-running prevention

### ISSUE THREAD

**Issue by obatirou** [pcaversaccio/create2deployer#84]
`Create2` opens the door to front running, hence, enforcing the salt to contain the `msg.sender` or having to pass a signature could be ways to resolve this issue.
* `msg.sender` implementation in [Create2Factory from Pr000xy repository](https://github.com/0age/Pr000xy/blob/c293074509c0f0d5fdf54c451ab39b2e00f48b7a/contracts/Create2Factory.sol#L108)
* signature implementation in [OZ article](https://blog.openzeppelin.com/getting-the-most-out-of-create2/)

It could be a problem to have a malicious address front-running the contract creation for reputation purpose only. 
Other than that, if I am not mistaken, it seems not to be a problem as you would get the exact same result contract wise.
I might be missing a case ?

What are your thoughts on this ?

**Comment by pcaversaccio** [comment]
@obatirou thanks for raising this issue. My thoughts:
-  The `msg.sender` of the contract creation transaction will always be the `create2deployer`. I highlight this as well [here](https://github.com/pcaversaccio/xdeployer#a-note-on-the-contract-creation-transaction). What you're actually referring to is `tx.origin`. This is however something I do highly discourage using due to certain security issues (some for instance [here](https://docs.soliditylang.org/en/v0.8.17/security-considerations.html#tx-origin)).
- Yes you could potentially resolve this via a signature implementation but I recommend doing a proper constructor setup instead. The only thing that will change if done correctly is the `tx.origin`. If someone uses the `tx.origin` in the constructor (I still discourage this) and someone frontruns the deployment, the `init_code` will change and therefore the address. So in the case a person frontruns the `CREATE2` deployment and wants to assure the exact same address, the only thing that will change is `tx.origin` (as mentioned above the `msg.sender` will stay the same) & the nonce (which is irrelevant here) and I don't see any issues with that.

**Comment by pcaversaccio** [comment]
Closing this issue since the risk is acceptable. For the sake of documentation, I recommend anyone that who wants to prevent this for sure using flashbots (or other MEV relay services) in combination with a bullet-proof constructor setup. To emphasise - if anyone frontruns you and gets the same contract address, the exact same bytecode has been deployed and the only potential difference is the `tx.origin`.

**Comment by pcaversaccio** [comment]
I have also discussed this [here](https://twitter.com/pcaversaccio/status/1585886172663816192).

**Comment by obatirou** [comment]
Thanks for your detailed answers !
I agree with all your points and I should have been more precise by adding the fact I was talking about `msg.sender` in the `deploy` fonction of the `create2deployer`, hence preventing a frontrun on `tx.origin` in the created contract. Allowing to be sure that only the one that needs to deploy the contract will do it when they want.
A case I had in mind was a protocol building in the open and deployer / multig of the project should be the only one submitting the call to `deploy` of `create2deployer` for reputation purposes.
After reflexion, this might be a false problem. And, like you said above and in your tweet, it is the project job to make the deployment safe from front-running.
